### ISSUE TITLE
App for others platforms

### ISSUE THREAD

**Issue by SilentReaction** [Wolfteam/Shiori#113] opened 2021-09-10 14:28 UTC
Hi, great app, I would like to know if maybe there is an iOS version for the future.

**Comment by TheToto** [comment] 2021-09-11 13:07
#38

**Comment by ashkryab-fl** [comment] 2021-09-17 19:49
Hi. I am also a flutter developer, I have a mac. I can build ios build and set up bitrise for. You only need an Apple developer account.

**Comment by Wolfteam** [comment] 2021-10-17 23:18
Duplicate of #38

**Closed by Wolfteam** 2021-10-17 23:18 UTC
